### ISSUE TITLE
Multiple Mac Address

### ISSUE THREAD

**Issue by PatrickDenis** [applericky/macpy#1]
Hi, Thanks for the nice break down of the script.

When doing multiple mac , we are getting an error from the API asking to register.
We did register for the 1000 free request per day but now they ask to add this :

To use the API you will need a bearer token included in your request's Authorization header.

They lost me on that part :)

**Comment by vimrichie** [comment]
Hi @PatrickDenis 

I can get something going for you. Do you have any example code you want me to modify as an example or would you prefer for me to create it?

**Comment by PatrickDenis** [comment]
I was able using the time module to make a delay,
But its because i have no clue how to add the authorization.

An exemple is enought :)


Sent from my iPhone

On Apr 4, 2022, at 8:37 PM, applericky ***@***.***> wrote:

﻿

Hi @PatrickDenis<https://github.com/PatrickDenis>

I can get something going for you. Do you have any example code you want me to modify as an example or would you prefer for me to create it?

**Comment by vimrichie** [comment]
@PatrickDenis 

If you are using the time module I'm wondering if the request is being sent multiple times at once and it might benefit from using some type of concurrency. I have a working example for you without concurrency. 


```
import sys
import requests

headers = {
    'Authorization': 'Bearer <your_really_long_token here>',
    'Accept': 'text/plain',
}

def searchmac():
    try:
        mac = input("Please enter the MAC Address: ")
        vendor = requests.get(f'https://api.macvendors.com/v1/lookup/{mac}', headers=headers).text
        if "Not Found" in vendor:
            print("MAC address not found.")
        elif len(mac) == 0:
            print("No Mac Address entered.")
        else:
            print(vendor)
    except IndexError as e:
        print("No MAC address entered.")

if __name__ == "__main__":
    searchmac()

```

All you have to do is add your token in the authorization part. 

`'Authorization': 'Bearer xxxxxxxxx12344556',`

Let me know if this works for you or if you need some type of modification. Thanks for waiting as I did not have my laptop the last few days.

**Comment by vimrichie** [comment]
@PatrickDenis 

Let me know if you have been able to test this.

**Comment by vimrichie** [comment]
Closing out. Provided a simple script to do the task with API token.
